/**
 * 大区 → 小区列表（用于筛选、正则 fallback；与 ZIP_TO_AREA 中的 area 对齐）
 */
export const AREA_MAP: Record<string, string[]> = {
  Manhattan: [
    "Midtown",
    "Upper East Side",
    "Upper West Side",
    "Harlem",
    "East Harlem",
    "Washington Heights",
    "Inwood",
    "Marble Hill",
    "FiDi",
    "Tribeca",
    "SoHo",
    "NoHo",
    "East Village",
    "West Village",
    "Greenwich Village",
    "Chelsea",
    "Hells Kitchen",
    "Murray Hill",
    "Gramercy",
    "Flatiron",
    "NoMad",
    "Kips Bay",
    "Stuyvesant Town",
    "Lower East Side",
    "Chinatown",
    "Battery Park City",
    "Hudson Yards",
    "Morningside Heights",
    "Hamilton Heights",
    "Sugar Hill",
    "Roosevelt Island",
  ],
  Brooklyn: [
    "Williamsburg",
    "DUMBO",
    "Downtown Brooklyn",
    "Brooklyn Heights",
    "Park Slope",
    "Prospect Heights",
    "Fort Greene",
    "Clinton Hill",
    "Bed-Stuy",
    "Bushwick",
    "Greenpoint",
    "Cobble Hill",
    "Boerum Hill",
    "Carroll Gardens",
    "Red Hook",
    "Sunset Park",
    "Bay Ridge",
    "Flatbush",
    "Crown Heights",
    "Prospect Lefferts Gardens",
    "Gowanus",
    "East New York",
    "Brownsville",
    "Kensington",
    "Bensonhurst",
    "Borough Park",
    "Gravesend",
    "Coney Island",
    "Sheepshead Bay",
    "Midwood",
    "Canarsie",
  ],
  Queens: [
    "LIC",
    "Long Island City",
    "Astoria",
    "Jackson Heights",
    "Flushing",
    "Forest Hills",
    "Rego Park",
    "Sunnyside",
    "Woodside",
    "Elmhurst",
    "Jamaica",
    "Bayside",
    "Fresh Meadows",
    "Ridgewood",
    "Maspeth",
  ],
  Bronx: [
    "South Bronx",
    "Mott Haven",
    "Fordham",
    "Riverdale",
    "Kingsbridge",
    "Pelham Bay",
    "Throgs Neck",
    "Morris Heights",
    "Baychester",
  ],
  "Staten Island": ["St. George", "Stapleton", "Todt Hill", "Rosebank"],
  "Jersey City": [
    "Journal Square",
    "Newport",
    "Downtown JC",
    "The Waterfront",
    "Paulus Hook",
    "Hamilton Park",
    "Bergen-Lafayette",
  ],
  Hoboken: ["Hoboken"],
  "Other NJ": ["Bayonne", "Edgewater", "Fort Lee", "Kearny", "Newark", "North Bergen", "Secaucus", "Union City", "Weehawken", "West New York"],
};
